version: '3.8' # Định phiên bản Docker Compose

services:
  app:
    build:
      context: . # Thư mục chứa Dockerfile
      dockerfile: Dockerfile # Tên file Dockerfile
    ports:
      - "8080:80" # Mapping port 8080 của máy host tới port 80 của container
