version: '3.4'

services:
  prod_cv_curriculum_vitae:
    image: prod_cv_curriculum_vitae
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
