version: '3'
services:
  app:
    image: cv_curriculum_vitae
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Ánh xạ port 8080 của container đến port 8080 của máy chủ
